version: '3.8'

services:
  fastapi:
    build:
      context: ./fastapi_app
    ports:
      - "8000:8000"
  
  streamlit:
    build:
      context: ./streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
